// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.17.3
// source: druid_field.proto

package protos

import (
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// dimensionsSpec
// Druid applies ingestion spec components in a particular order: first flattenSpec (if any),
// then timestampSpec, then transformSpec, and finally dimensionsSpec and metricsSpec
type DruidDimensionOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// if not set use previous step name
	Name               string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	MultiValueHandling string `protobuf:"bytes,2,opt,name=multi_value_handling,json=multiValueHandling,proto3" json:"multi_value_handling,omitempty"`
	CreateBitmapIndex  bool   `protobuf:"varint,3,opt,name=create_bitmap_index,json=createBitmapIndex,proto3" json:"create_bitmap_index,omitempty"`
}

func (x *DruidDimensionOptions) Reset() {
	*x = DruidDimensionOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_druid_field_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DruidDimensionOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DruidDimensionOptions) ProtoMessage() {}

func (x *DruidDimensionOptions) ProtoReflect() protoreflect.Message {
	mi := &file_druid_field_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DruidDimensionOptions.ProtoReflect.Descriptor instead.
func (*DruidDimensionOptions) Descriptor() ([]byte, []int) {
	return file_druid_field_proto_rawDescGZIP(), []int{0}
}

func (x *DruidDimensionOptions) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DruidDimensionOptions) GetMultiValueHandling() string {
	if x != nil {
		return x.MultiValueHandling
	}
	return ""
}

func (x *DruidDimensionOptions) GetCreateBitmapIndex() bool {
	if x != nil {
		return x.CreateBitmapIndex
	}
	return false
}

// flattenSpec
type DruidFlattenOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Expr string `protobuf:"bytes,4,opt,name=expr,proto3" json:"expr,omitempty"`
}

func (x *DruidFlattenOptions) Reset() {
	*x = DruidFlattenOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_druid_field_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DruidFlattenOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DruidFlattenOptions) ProtoMessage() {}

func (x *DruidFlattenOptions) ProtoReflect() protoreflect.Message {
	mi := &file_druid_field_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DruidFlattenOptions.ProtoReflect.Descriptor instead.
func (*DruidFlattenOptions) Descriptor() ([]byte, []int) {
	return file_druid_field_proto_rawDescGZIP(), []int{1}
}

func (x *DruidFlattenOptions) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *DruidFlattenOptions) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DruidFlattenOptions) GetExpr() string {
	if x != nil {
		return x.Expr
	}
	return ""
}

// timestampSpec
type DruidTimestampOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Format string `protobuf:"bytes,1,opt,name=format,proto3" json:"format,omitempty"`
}

func (x *DruidTimestampOptions) Reset() {
	*x = DruidTimestampOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_druid_field_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DruidTimestampOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DruidTimestampOptions) ProtoMessage() {}

func (x *DruidTimestampOptions) ProtoReflect() protoreflect.Message {
	mi := &file_druid_field_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DruidTimestampOptions.ProtoReflect.Descriptor instead.
func (*DruidTimestampOptions) Descriptor() ([]byte, []int) {
	return file_druid_field_proto_rawDescGZIP(), []int{2}
}

func (x *DruidTimestampOptions) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

var file_druid_field_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptor.FieldOptions)(nil),
		ExtensionType: (*DruidDimensionOptions)(nil),
		Field:         2021,
		Name:          "gen_druid_schema.dimension",
		Tag:           "bytes,2021,opt,name=dimension",
		Filename:      "druid_field.proto",
	},
	{
		ExtendedType:  (*descriptor.FieldOptions)(nil),
		ExtensionType: (*DruidFlattenOptions)(nil),
		Field:         2022,
		Name:          "gen_druid_schema.flatten",
		Tag:           "bytes,2022,opt,name=flatten",
		Filename:      "druid_field.proto",
	},
	{
		ExtendedType:  (*descriptor.FieldOptions)(nil),
		ExtensionType: (*DruidTimestampOptions)(nil),
		Field:         2023,
		Name:          "gen_druid_schema.timestamp_spec",
		Tag:           "bytes,2023,opt,name=timestamp_spec",
		Filename:      "druid_field.proto",
	},
}

// Extension fields to descriptor.FieldOptions.
var (
	// BigQuery field schema generation options.
	//
	// optional gen_druid_schema.DruidDimensionOptions dimension = 2021;
	E_Dimension = &file_druid_field_proto_extTypes[0]
	// optional gen_druid_schema.DruidFlattenOptions flatten = 2022;
	E_Flatten = &file_druid_field_proto_extTypes[1]
	// optional gen_druid_schema.DruidTimestampOptions timestamp_spec = 2023;
	E_TimestampSpec = &file_druid_field_proto_extTypes[2]
)

var File_druid_field_proto protoreflect.FileDescriptor

var file_druid_field_proto_rawDesc = []byte{
	0x0a, 0x11, 0x64, 0x72, 0x75, 0x69, 0x64, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x10, 0x67, 0x65, 0x6e, 0x5f, 0x64, 0x72, 0x75, 0x69, 0x64, 0x5f, 0x73,
	0x63, 0x68, 0x65, 0x6d, 0x61, 0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8d, 0x01, 0x0a, 0x15, 0x44, 0x72, 0x75, 0x69,
	0x64, 0x44, 0x69, 0x6d, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x30, 0x0a, 0x14, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x5f, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x5f, 0x68, 0x61, 0x6e, 0x64, 0x6c, 0x69, 0x6e, 0x67, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x12, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x48,
	0x61, 0x6e, 0x64, 0x6c, 0x69, 0x6e, 0x67, 0x12, 0x2e, 0x0a, 0x13, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x5f, 0x62, 0x69, 0x74, 0x6d, 0x61, 0x70, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x11, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x42, 0x69, 0x74, 0x6d,
	0x61, 0x70, 0x49, 0x6e, 0x64, 0x65, 0x78, 0x22, 0x51, 0x0a, 0x13, 0x44, 0x72, 0x75, 0x69, 0x64,
	0x46, 0x6c, 0x61, 0x74, 0x74, 0x65, 0x6e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x65, 0x78, 0x70, 0x72, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x65, 0x78, 0x70, 0x72, 0x22, 0x2f, 0x0a, 0x15, 0x44, 0x72,
	0x75, 0x69, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x4f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x3a, 0x65, 0x0a, 0x09, 0x64,
	0x69, 0x6d, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1d, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64,
	0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xe5, 0x0f, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27,
	0x2e, 0x67, 0x65, 0x6e, 0x5f, 0x64, 0x72, 0x75, 0x69, 0x64, 0x5f, 0x73, 0x63, 0x68, 0x65, 0x6d,
	0x61, 0x2e, 0x44, 0x72, 0x75, 0x69, 0x64, 0x44, 0x69, 0x6d, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e,
	0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x09, 0x64, 0x69, 0x6d, 0x65, 0x6e, 0x73, 0x69,
	0x6f, 0x6e, 0x3a, 0x5f, 0x0a, 0x07, 0x66, 0x6c, 0x61, 0x74, 0x74, 0x65, 0x6e, 0x12, 0x1d, 0x2e,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e,
	0x46, 0x69, 0x65, 0x6c, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xe6, 0x0f, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x67, 0x65, 0x6e, 0x5f, 0x64, 0x72, 0x75, 0x69, 0x64, 0x5f,
	0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x2e, 0x44, 0x72, 0x75, 0x69, 0x64, 0x46, 0x6c, 0x61, 0x74,
	0x74, 0x65, 0x6e, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x07, 0x66, 0x6c, 0x61, 0x74,
	0x74, 0x65, 0x6e, 0x3a, 0x6e, 0x0a, 0x0e, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x5f, 0x73, 0x70, 0x65, 0x63, 0x12, 0x1d, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x18, 0xe7, 0x0f, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x67, 0x65,
	0x6e, 0x5f, 0x64, 0x72, 0x75, 0x69, 0x64, 0x5f, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x2e, 0x44,
	0x72, 0x75, 0x69, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x4f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x52, 0x0d, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x53,
	0x70, 0x65, 0x63, 0x42, 0x38, 0x5a, 0x36, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x6e, 0x67, 0x75, 0x79, 0x65, 0x6e, 0x73, 0x69, 0x6e, 0x68, 0x74, 0x75, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2d, 0x67, 0x65, 0x6e, 0x2d, 0x64, 0x72, 0x75, 0x69, 0x64, 0x2d,
	0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_druid_field_proto_rawDescOnce sync.Once
	file_druid_field_proto_rawDescData = file_druid_field_proto_rawDesc
)

func file_druid_field_proto_rawDescGZIP() []byte {
	file_druid_field_proto_rawDescOnce.Do(func() {
		file_druid_field_proto_rawDescData = protoimpl.X.CompressGZIP(file_druid_field_proto_rawDescData)
	})
	return file_druid_field_proto_rawDescData
}

var file_druid_field_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_druid_field_proto_goTypes = []interface{}{
	(*DruidDimensionOptions)(nil),   // 0: gen_druid_schema.DruidDimensionOptions
	(*DruidFlattenOptions)(nil),     // 1: gen_druid_schema.DruidFlattenOptions
	(*DruidTimestampOptions)(nil),   // 2: gen_druid_schema.DruidTimestampOptions
	(*descriptor.FieldOptions)(nil), // 3: google.protobuf.FieldOptions
}
var file_druid_field_proto_depIdxs = []int32{
	3, // 0: gen_druid_schema.dimension:extendee -> google.protobuf.FieldOptions
	3, // 1: gen_druid_schema.flatten:extendee -> google.protobuf.FieldOptions
	3, // 2: gen_druid_schema.timestamp_spec:extendee -> google.protobuf.FieldOptions
	0, // 3: gen_druid_schema.dimension:type_name -> gen_druid_schema.DruidDimensionOptions
	1, // 4: gen_druid_schema.flatten:type_name -> gen_druid_schema.DruidFlattenOptions
	2, // 5: gen_druid_schema.timestamp_spec:type_name -> gen_druid_schema.DruidTimestampOptions
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	3, // [3:6] is the sub-list for extension type_name
	0, // [0:3] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_druid_field_proto_init() }
func file_druid_field_proto_init() {
	if File_druid_field_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_druid_field_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DruidDimensionOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_druid_field_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DruidFlattenOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_druid_field_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DruidTimestampOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_druid_field_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 3,
			NumServices:   0,
		},
		GoTypes:           file_druid_field_proto_goTypes,
		DependencyIndexes: file_druid_field_proto_depIdxs,
		MessageInfos:      file_druid_field_proto_msgTypes,
		ExtensionInfos:    file_druid_field_proto_extTypes,
	}.Build()
	File_druid_field_proto = out.File
	file_druid_field_proto_rawDesc = nil
	file_druid_field_proto_goTypes = nil
	file_druid_field_proto_depIdxs = nil
}
